name: Release tagger
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'tagger action (promote | rollback)'
        required: true
      head:
        description: 'head AMP version'
        required: true
      base:
        description: 'base AMP version'
        required: true
      channel:
        description: 'release channel (beta-opt-in | beta-percent | stable | lts)'
        required: true
      sha:
        description: 'commit sha'
        required: true
permissions:
  contents: read

jobs:
  tagger:
    environment: release_tagger
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: bash ./.github/workflows/install_dependencies.sh
      - name: Run tagger
        run: |
          node ./build-system/release-tagger/index.js \
            --action ${{ github.event.inputs.action }} \
            --head ${{ github.event.inputs.head }} \
            --base ${{ github.event.inputs.base }} \
            --channel ${{ github.event.inputs.channel }} \
            --sha ${{ github.event.inputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}

  create-issue-on-error:
    if: failure()
    needs: tagger
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    environment: create_issue_on_error
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create issue on error
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        with:
          filename: .github/create_issue_on_error.md
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
          WORKFLOW_NAME: ${{ github.workflow }}
          MENTION: '@ampproject/wg-infra'
          REPO_SLUG: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
