name: Update status.amp.dev
on:
  issues:
    types: [opened]
  issue_comment:
    types: [edited]
permissions:
  contents: read

jobs:
  status-page:
    if: contains(github.event.issue.title, '🌸 Cherry-pick request')
    runs-on: ubuntu-latest
    environment: status_page
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Add progress comment to cherry-pick issue for Stable and LTS
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          npm ci
          node ./build-system/status-page/comment.js ${{ github.event.issue.number }} ${{ github.actor }}
        env:
          BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
      - name: Sync status page with cherry-pick progress
        if: github.event_name == 'issue_comment' && github.event.action == 'edited' && contains(github.event.comment.body, '🌸 Cherry-pick Progress 🌸')
        run: |
          npm ci
          node ./build-system/status-page/incident.js ${{ github.event.issue.number }}
        env:
          BODY: ${{ github.event.issue.body }}
          COMMENT_BEFORE: ${{ github.event.changes.body.from }}
          COMMENT_AFTER: ${{ github.event.comment.body }}
          STATUS_PAGE_ID: ${{ secrets.STATUS_PAGE_ID }}
          STATUS_PAGE_TOKEN: ${{ secrets.STATUS_PAGE_TOKEN }}

  create-issue-on-error:
    if: failure()
    needs: status-page
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    environment: create_issue_on_error
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create issue on error
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        with:
          filename: .github/create_issue_on_error.md
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
          WORKFLOW_NAME: ${{ github.workflow }}
          MENTION: '@ampproject/wg-infra'
          REPO_SLUG: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
