name: Update Session Issues

on:
  # This schedule should match the time rotation configured on
  # update-design-review-issues.js.
  # Times correspond to session end, and additionally 1 hour earlier to account
  # for Daylight Savings.
  schedule:
    - cron: '30 16,17 * * 3' # Africa/Europe/western Asia
    - cron: '0 21,22 * * 3' # Americas

permissions:
  contents: read

jobs:
  update-session-issues:
    permissions:
      issues: write
    if: github.repository == 'ampproject/amphtml'
    name: Update Session Issues
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Update Session Issues
        run: |
          node ./build-system/common/update-session-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
